[package]
name    = "shotmarker-csv-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "*"
nom    = "8.0.0"
# nom-tracer isn't compatible with nom 8.0.0 yet, and only works with 7.x at most.
# nom-tracer = { version = "1.0.1", features = ["trace-color", "trace-context"] }
remain    = "0.2.14"
thiserror = "2.0.11"
