[tools]
rust             = "nightly-2025-02-28"
"cargo:trunk"    = "0.21.7"
"cargo:sqlx-cli" = "0.8.3"
"cargo:yew-fmt"  = "0.5.5"
node             = "23.9.0"
npm              = "11.1.0"

[tasks.ui-node-dependencies]
description = "Download node module dependencies"
run         = "npm ci"
dir         = "ui"

[tasks.ui-rust-wasm-target]
description = "Install wasm32 rust target"
run         = "rustup target add wasm32-unknown-unknown"

[tasks.ui-build]
description = "Debug: Build web frontend"
run         = "trunk build"
dir         = "ui"

[tasks.ui-build-release]
description = "Release: Build web frontend"
run         = "trunk build --release --cargo-profile wasm-release"
dir         = "ui"

[tasks.ui-serve]
description = "Serve UI via trunk"
run         = "trunk serve"
dir         = "ui"

[tasks.server-build]
description = "Debug: Build API server"
run         = "cargo build"
dir         = "server"

[tasks.server-build-release]
description = "Release: Build API server"
run         = "cargo build --release"
dir         = "server"
