[package]
name              = "xtask"
authors.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
